CREATE TABLE IF NOT EXISTS score
(
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    volume INTEGER NOT NULL ,
    subject_id INTEGER NOT NULL REFERENCES subject(id)
);

CREATE TABLE IF NOT EXISTS subject
(
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT NOT NULL ,
    student_id INTEGER NOT NULL REFERENCES student(id)
);

CREATE TABLE IF NOT EXISTS student
(
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT NOT NULL
);
